### ISSUE TITLE
Missing Files 2 folders 

### ISSUE THREAD

**Issue by NageshCodeRider** [worldsat/project194#1]
This best project in detail but two folders are missing in github repository: Name:"drawable-xxhdpi" and "drawable-xxxhdpi" 
![Screenshot 2024-07-30 195348](https://github.com/user-attachments/assets/821f82ea-e4fd-4dab-bc1f-6e374f90c55d)
please let we what is present in that folder

**Comment by worldsat** [comment]
The folders have been uploaded
